services:
  - type: web
    name: homeflow-backend
    runtime: node
    buildCommand: npm install
    startCommand: node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: ENCRYPTION_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: homeflow-db
          property: connectionString
      - key: REDIS_URL
        value: redis://localhost:6379
      - key: WS_PORT
        value: 3001

databases:
  - name: homeflow-db
    databaseName: homeflow
    user: homeflow